# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            am8i/rotten-potatoes:latest
            am8i/rotten-potatoes:${{ github.run_number }}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: ${{ secrets.AZURE_K8S_CREDENTIALS }} 
          # Resource Group Name
          resource-group: RG01
          # AKS Cluster Name
          cluster-name: test01
      - name: Deploy Mongo
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/mongodb/deployment.yaml
            k8s/mongodb/service.yaml
      - name: Deploy App
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/app/deployment.yaml
            k8s/app/service.yaml
          images: am8i/rotten-potatoes:${{ github.run_number }}
